[profile.default]
src = 'src'
verbosity = 2
libs = ['lib']
out = 'out/artifacts'
build_info_path = 'out/artifacts/build-info'
ffi = true
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read", path = "./"}]
ignored_error_codes = [1878, 5574, 2519]
force = true

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
homestead = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
optimism = "${RPC_OPTIMISM}"
optimism-goerli = "${RPC_OPTIMISM_GOERLI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum-goerli = "${RPC_ARBITRUM_GOERLI}"
matic = "${RPC_MATIC}"
maticmum = "${RPC_MATIC_MUMBAI}"